# Latent Brownian Bridge Diffusion Model Template(Latent Space)
runner: "BBDMRunner"
training:
  n_epochs: 100
  n_steps: 200000
  save_interval: 2
  sample_interval: 2
  validation_interval: 2
  accumulate_grad_batches: 4

testing:
  clip_denoised: False
  sample_num: 5

data:
  dataset_name: 'dataset_name'
  dataset_type: 'custom_aligned'
  dataset_config:
    dataset_path: '/mnt/hmi/thuong/wb_train_val_test_dataset/'
    image_size: 512
    channels: 1
    to_normal: False
    flip: True
  train:
    batch_size: 16
    shuffle: True
  val:
    batch_size: 16
    shuffle: True
  test:
    batch_size: 16
    # shuffle: False

model:
  model_name: "LBBDM-f8-condition-longer-adamw-autoencoder" # part of result path
  model_type: "LBBDM" # specify a module
  latent_before_quant_conv: False
  normalize_latent: False
  only_load_latent_mean_std: False
  # model_load_path:  # model checkpoint path
  # optim_sche_load_path:  # optimizer scheduler checkpoint path

  EMA:
    use_ema: True
    ema_decay: 0.995
    update_ema_interval: 8 # step
    start_ema_step: 30000

  CondStageParams:
    n_stages: 3
    in_channels: 1
    out_channels: 1

  VQGAN:
    params_print:
      ckpt_path: '/mnt/thuong_mocban/taming-transformers/logs/2024-01-20T06-55-04_print_woodblock_vqgan/checkpoints/last.ckpt'
      embed_dim: 4
      n_embed: 16384
      ddconfig:
        double_z: false
        z_channels: 4
        resolution: 512
        in_channels: 1
        out_ch: 1
        ch: 128
        ch_mult: !!python/tuple
          - 1
          - 1
          - 2
          - 2
          - 4
        num_res_blocks: 2
        attn_resolutions:
          - 32
        dropout: 0.0

      lossconfig:
        target: torch.nn.Identity

    params_depth:
      ckpt_path: '/mnt/thuong_mocban/taming-transformers/logs/2024-01-22T20-19-51_depth_woodblock_vqgan/checkpoints/last.ckpt'
      embed_dim: 4
      n_embed: 16384
      ddconfig:
        double_z: false
        z_channels: 4
        resolution: 256
        in_channels: 1
        out_ch: 1
        ch: 128
        ch_mult: !!python/tuple
          - 1
          - 1
          - 2
          - 2
          - 4
        num_res_blocks: 2
        attn_resolutions:
          - 32
        dropout: 0.0

      lossconfig:
        target: torch.nn.Identity

  BB:
    optimizer:
      weight_decay: 0.0001
      optimizer: 'AdamW'
      lr: 5.e-5
      beta1: 0.9

    lr_scheduler:
      factor: 0.5
      patience: 3000
      threshold: 0.0001
      cooldown: 3000
      min_lr: 5.e-7

    params:
      mt_type: 'linear' # options {'linear', 'sin'}
      objective: 'grad' # options {'grad', 'noise', 'ysubx'}
      loss_type: 'l1' # options {'l1', 'l2'}

      skip_sample: True
      sample_type: 'linear' # options {"linear", "sin"}
      sample_step: 200

      num_timesteps: 1000 # timesteps
      eta: 1.0 # DDIM reverse process eta
      max_var: 1.0 # maximum variance

      UNetParams:
        image_size: 32
        in_channels: 8
        model_channels: 128
        out_channels: 4
        num_res_blocks: 2
        attention_resolutions: !!python/tuple
          - 32
          - 16
          - 8
        channel_mult: !!python/tuple
          - 1
          - 4
          - 8
        conv_resample: True
        dims: 2
        num_heads: 32
        num_head_channels: 64
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: True
        context_dim: 4
        condition_key: "first_stage" # options {"SpatialRescaler", "first_stage", "nocond"}